name: koi-auction CI

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: "whysofail/koi-auction"

jobs:
  amd64:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: production  # Specify the environment
    steps:
      - uses: actions/checkout@v3

      # Login to GitHub Container Registry
      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      # Build and Push Docker Image
      - name: Build and push expressjs image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # Trigger Coolify Deployment
      # - name: Rebuild and redeploy app in Coolify
      #   run: |
      #     curl --request GET '${{ secrets.COOLIFY_DEV_WEBHOOK_URL }}' \
      #          --header 'Authorization: Bearer ${{ secrets.COOLIFY_WEBHOOK_TOKEN }}'
